### ISSUE TITLE
issue_delay

### ISSUE THREAD

**Issue by pranavr2003** [Siddhesh-Agarwal/Snake-game#1]
The speedup time of the snake is too slow, I made it -0.008
Plus, the food is virtually impossible to get when it's on the border, unless it's speedup time is like, 0.01, which is too slow
So I changed the co-ordinates of the food placement _randint_ from (-290, 290) to (-280, 280), so that the food never clashes with the border

Check line 150
line 128-130

Update them asap

![pyth1](https://user-images.githubusercontent.com/56883253/91682298-b55e2f80-eb6e-11ea-91f7-3cbf8609f59f.JPG)
![pyth2](https://user-images.githubusercontent.com/56883253/91682305-b8592000-eb6e-11ea-83bd-4923f8636f97.JPG)

**Comment by Siddhesh-Agarwal** [comment]
I considered the fact that food could be close to border and the range was given as (-290, 290) because, I am not checking if the distance between food and head is zero. Instead, I am checking If the distance is less than 20. So you don't need to worry if the food is on the border because you can still collect it.

**Comment by pranavr2003** [comment]
I know I can collect the food even on the border, I even did it. I'm just saying it's kinda hard to do it, even with the delay time already given. Plus, it's inefficient that way.
